apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: default
data:
  fluent.conf: |
    <label @FLUENT_LOG>
      <match fluent.**>
        @type null
        @id ignore_fluent_logs
      </match>
    </label>
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*helm*.log
      pos_file /var/log/fluentd.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%L%z
        keep_time_key true
      </parse>
    </source>
    <match kubernetes.**>
      @type             elasticsearch
      @log_level        debug
      include_tag_key   false
      host              116.103.226.146
      port              9200
      scheme            https
      ssl_verify        false
      user              elastic
      password          iRsUoyhqW-CyyGdwk6V_
      logstash_format   true
      logstash_prefix   tuan_79219430423
      reload_connections true
      reconnect_on_error true
      reload_on_failure true
      request_timeout 20s
      <buffer>
        flush_interval 10s
      </buffer>
    </match>
