apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: vdt-prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: vdt
  resources:
    requests:
      memory: 200Mi
  enableAdminAPI: false