apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helm-web-monitor 
  labels:
    app: vdt
spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: nginx-exporter
  namespaceSelector:
    matchNames:
    - default  
  endpoints:
  - port: http  
    path: /metrics  
    interval: 30s 